### ISSUE TITLE
The Jupyter binder returns "400 bad request"

### ISSUE THREAD

**Issue by JJ** [p6steve/perl6-Physics-Measure#10]
If you follow the suggestion, it kinda displays something, but I'm not sure it's what we want.

**Comment by p6steve** [comment]
Dear JJ - thank you very much for trying and apologies for the error - I have decided to separate the Jupyter/Binder consumption into a new GitHub project. That way it is more likely to have a pre-built image and start more quickly. Would you mind going over to https://github.com/p6steve/perl6-Physics-Measure-JupyterBinder and clicking the Binder badge over there? 

I just tested and is alive and well - so please do let me know your success and then hopefully I can close this issue...

**Comment by p6steve** [comment]
Hi JJ - hoping that this worked for you - will close the issue now.

**Comment by JJ** [comment]
It does, thanks!
